name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depend: [ PlaceholderAPI, Milkshake-Bukkit ]
commands:
  prefixchanger:
    aliases: [ "prefix" ]
    description: Open the PrefixChanger menu